<?php

namespace AppBundle\Repository;

/**
 * CartLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartLineRepository extends \Doctrine\ORM\EntityRepository
{
}
