<?php

namespace AppBundle\Repository;

/**
 * CheckModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckModeRepository extends \Doctrine\ORM\EntityRepository
{
}
