<?php

namespace AppBundle\Repository;

/**
 * ClientConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientConnectedRepository extends \Doctrine\ORM\EntityRepository
{
}
