<?php

namespace AppBundle\Repository;

/**
 * Command_facturationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Command_facturationRepository extends \Doctrine\ORM\EntityRepository
{
}
