<?php

namespace AppBundle\Repository;

/**
 * IrrigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IrrigationRepository extends \Doctrine\ORM\EntityRepository
{
}
