<?php

namespace AppBundle\Repository;

/**
 * OtherModRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherModRepository extends \Doctrine\ORM\EntityRepository
{
}
