<?php

namespace AppBundle\Repository;

/**
 * PaypalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalRepository extends \Doctrine\ORM\EntityRepository
{
}
