<?php

namespace AppBundle\Repository;

/**
 * ResistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
