app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

products:
    type:     rest
    resource: AppBundle\Controller\ProductController    

irrigations:
    type:     rest
    resource: AppBundle\Controller\IrrigationController  

expositions:
    type:     rest
    resource: AppBundle\Controller\ExpositionController  

resistances:
    type:     rest
    resource: AppBundle\Controller\ResistanceController  

soils:
    type:     rest
    resource: AppBundle\Controller\SoilController      