AppBundle\Entity\Product:
  attributes:
    name:
      groups : ['product'] 
    description : 
      groups : ['product']
    price:
      groups : ['product']
    brand :
      groups : ['product']
    isPremium :
      groups : ['product']
    onSold :
      groups : ['product']
    vendor :
      groups : ['product']
    note :
      groups : ['product']
    numberOfProducts :
      groups : ['product']
    numberOfVote : 
      groups : ['product']
    numberOfComments :
      groups : ['product']
    variety :
      groups : ['product']
    seedPeriod :
      groups : ['product']
    species :
      groups : ['product']
    type :
      groups : ['product']
    harvest :
      groups : ['product']
    carving :
      groups : ['product']
    treatment :
      groups : ['product']
    fertilize :
      groups : ['product']
    cover : 
      groups : ['product']
    file :
      groups : ['product']

AppBundle\Entity\Soil:
  attributes:
    label:
      groups : ['product']
    
AppBundle\Entity\Resistance:
  attributes:
    label:
      groups : ['product']
    
AppBundle\Entity\Irrigation:
  attributes:
    label:
      groups : ['product']
    
AppBundle\Entity\Exposition:
  attributes:
    label:
      groups : ['product']
    